config/routes.rb
Rails.application.routes.draw do
  # For common users
  scope module: "web" do
    constraints subdomain: "www" do
      root to: "home#index"

      get    "login",  to: "sessions#new",     as: :login
      delete "logout", to: "sessions#destroy", as: :logout

      get "confirmations", to: "confirmations#create", as: :confirmations

      # resources :bookings, only: %i(index edit update destroy)
      resources :sessions, only: %i(create)
      # resources :studios, only: %i(index show) do
      #   scope module: :studios do
      #     resources :bookings, only: %i(new create)
      #   end
      # end
      resources :users, only: %i(new create)

      resource :resend_confirmation_email, only: %i(new create)
      resource :setting, only: %i(edit update)
    end
  end

  # For studio staff
  scope module: "biz", as: :biz do
    constraints subdomain: "biz" do
      root to: "home#index"

      get    "login",  to: "sessions#new"
      delete "logout", to: "sessions#destroy"

      # resources :bookings, only: %i(index show)
      resources :sessions, only: %i(create)
      # resources :staff_members
      # resources :studios do
      #   scope module: :studios do
      #     resources :bookings
      #     resources :rooms
      #   end
      # end

      # resource :company, only: %i(show edit update)
      # resource :setting, only: %i(edit update)
    end
  end

  # For administrator
  scope module: "admin", as: :admin do
    constraints subdomain: "admin" do
      root to: "home#index"

      get    "login",  to: "sessions#new"
      delete "logout", to: "sessions#destroy"

      # resources :admin_users
      resources :companies do
        scope module: :companies do
          resources :staff_members, only: %i(new create)
        end
      end
      resources :sessions, only: %i(create)
      resources :staff_members, only: %i(index show edit update destroy)
    end
  end
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :staff_members
  # has_many :studios

  validates :name,       presence: true
  validates :tel,        presence: true
  validates :email,      presence: true
  validates :address,    presence: true
  validates :founded_at, presence: true
end

app/controllers/admin/companies/staff_members_controller.rb
class Admin::Companies::StaffMembersController < Admin::BaseController
  # GET /companies/:company_id/staff_members/new
  def new
    @staff_member = StaffMember.new(company_id: params[:company_id])
  end

  # POST /companies/:company_id/staff_members
  def create
    @staff_member = StaffMember.new(
      staff_member_params.merge(company_id: params[:company_id])
    )
    password = @staff_member.generate_random_password
    if @staff_member.save
      redirect_to admin_staff_member_path(@staff_member), notice: "Created: password=#{password}"
    else
      render :new
    end
  end

  private

  def staff_member_params
    params.require(:staff_member).permit(:username, :email)
  end
end

app/controllers/admin/companies_controller.rb
class Admin::CompaniesController < Admin::BaseController
  # GET /companies
  def index
    @companies = Company.all.order(id: :desc)
  end

  # GET /companies/:id
  def show
    @company = Company.find(params[:id])
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # POST /companies
  def create
    @company = Company.new(company_params)
    if @company.save
      redirect_to admin_company_path(@company), notice: t("created")
    else
      render :new
    end
  end

  # GET /companies/:id/edit
  def edit
    @company = Company.find(params[:id])
  end

  # PATCH /companies/:id
  def update
    @company = Company.find(params[:id])
    if @company.update(company_params)
      redirect_to admin_company_path(@company), notice: t("updated")
    else
      render :edit
    end
  end

  # DELETE /companies/:id
  def destroy
    Company.destroy(params[:id])
    redirect_to admin_companies_path, notice: t("deleted")
  end

  private

  def company_params
    params.require(:company)
      .permit(:name, :tel, :email, :address, :founded_at)
  end
end

app/views/admin/companies/_form.html.erb
<% company = local_assigns[:company] %>

<%= form_with model: [:admin, company], local: true do |f| %>
  <%= render "shared/model_errors", model: company %>

  <div class="field">
    <%= f.label :name, class: "label" %>
    <%= f.text_field :name, class: "input" %>
  </div>

  <div class="field">
    <%= f.label :tel, class: "label" %>
    <%= f.telephone_field :tel, class: "input", placeholder: "03-1111-1111" %>
  </div>

  <div class="field">
    <%= f.label :email, class: "label" %>
    <%= f.email_field :email, class: "input" %>
  </div>

  <div class="field">
    <%= f.label :address, class: "label" %>
    <%= f.text_field :address, class: "input", placeholder: "111-1111 Shibuya, Tokyo" %>
  </div>

  <div class="field">
    <%= f.label :founded_at, class: "label" %>
    <%= f.date_field :founded_at, class: "input" %>
  </div>

  <div class="field">
    <div class="control">
      <%= f.submit nil, class: "button is-link" %>
    </div>
  </div>
<% end %>

app/views/admin/companies/edit.html.erb
<h1 class="title"><%= t ".title" %></h1>

<div class="content is-medium">
  <%= render "form", company: @company %>
</div>

app/views/admin/companies/index.html.erb
<div class="level">
  <div class="level-left">
    <h1 class="title"><%= t ".title" %></h1>
  </div>
  <div class="level-right">
    <%= link_to t("admin.companies.new.title"), new_admin_company_path, class: "button is-primary" %>
  </div>
</div>

<div class="content is-medium">
  <table class="table is-striped is-hoverable">
    <thead>
      <tr>
        <th><%= t "id" %></th>
        <th><%= t "activerecord.attributes.company.name" %></th>
        <th><%= t "activerecord.attributes.company.address" %></th>
        <th><%= t "activerecord.attributes.company.founded_at" %></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @companies.each do |company| %>
        <tr>
          <th><%= company.id %></th>
          <td><%= company.name %></td>
          <td><%= company.address %></td>
          <td><%= company.founded_at %></td>
          <td>
            <div class="columns">
            <div class="column">
            <%= link_to t("show"), admin_company_path(company), class: "button" %>
            </div>
            <div class="column">
            <%= link_to t("edit"), edit_admin_company_path(company), class: "button" %>
            </div>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/companies/new.html.erb
<h1 class="title"><%= t ".title" %></h1>

<div class="content is-medium">
  <%= render "form", company: @company %>
</div>

app/views/admin/companies/show.html.erb
<div class="level">
  <div class="level-left">
    <h1 class="title">ID: <%= @company.id %> - <%= @company.name %></h1>
  </div>
  <div class="level-right">
    <div class="columns">
      <div class="column">
        <%= link_to t("admin.companies.staff_members.new.title"), new_admin_company_staff_member_path(@company), class: "button is-primary" %>
      </div>
      <div class="column">
        <%= link_to t("edit"), edit_admin_company_path(@company), class: "button" %>
      </div>
      <div class="column">
        <%= link_to t("delete"), admin_company_path(@company), class: "button is-danger", method: :delete, data: { confirm: t("delete_confirm") } %>
      </div>
    </div>
  </div>
</div>

<div class="content is-small">
  <% %i(name tel email address founded_at).each do |attribute| %>
    <h3><%= t "activerecord.attributes.company.#{attribute}" %></h3>
    <p><%= @company.public_send(attribute) %></p>
  <% end %>
</div>