config/routes.rb
Rails.application.routes.draw do
  # For common users
  scope module: "web" do
    constraints subdomain: "www" do
      root to: "home#index"

      get    "login",  to: "sessions#new",     as: :login
      delete "logout", to: "sessions#destroy", as: :logout

      get "confirmations", to: "confirmations#create", as: :confirmations

      # resources :bookings, only: %i(index edit update destroy)
      resources :sessions, only: %i(create)
      # resources :studios, only: %i(index show) do
      #   scope module: :studios do
      #     resources :bookings, only: %i(new create)
      #   end
      # end
      resources :users, only: %i(new create)

      resource :resend_confirmation_email, only: %i(new create)
      resource :setting, only: %i(edit update)
    end
  end

  # For studio staff
  scope module: "biz", as: :biz do
    constraints subdomain: "biz" do
      root to: "home#index"

      get    "login",  to: "sessions#new"
      delete "logout", to: "sessions#destroy"

      # resources :bookings, only: %i(index show)
      resources :sessions, only: %i(create)
      # resources :staff_members
      # resources :studios do
      #   scope module: :studios do
      #     resources :bookings
      #     resources :rooms
      #   end
      # end

      # resource :company, only: %i(show edit update)
      # resource :setting, only: %i(edit update)
    end
  end

  # For administrator
  scope module: "admin", as: :admin do
    constraints subdomain: "admin" do
      root to: "home#index"

      get    "login",  to: "sessions#new"
      delete "logout", to: "sessions#destroy"

      # resources :admin_users
      resources :companies do
        scope module: :companies do
          resources :staff_members, only: %i(new create)
        end
      end
      resources :sessions, only: %i(create)
      resources :staff_members, only: %i(index show edit update destroy)
    end
  end
end

app/models/staff_member.rb
class StaffMember < ApplicationRecord
  include EmailRegisterable

  belongs_to :company

  validates :username, presence: true, uniqueness: true, length: { maximum: 16 }

  # @return [String]
  def generate_random_password
    password = SecureRandom.hex(4)
    self.password = self.password_confirmation = password
  end
end

app/controllers/admin/companies/staff_members_controller.rb
class Admin::Companies::StaffMembersController < Admin::BaseController
  # GET /companies/:company_id/staff_members/new
  def new
    @staff_member = StaffMember.new(company_id: params[:company_id])
  end

  # POST /companies/:company_id/staff_members
  def create
    @staff_member = StaffMember.new(
      staff_member_params.merge(company_id: params[:company_id])
    )
    password = @staff_member.generate_random_password
    if @staff_member.save
      redirect_to admin_staff_member_path(@staff_member), notice: "Created: password=#{password}"
    else
      render :new
    end
  end

  private

  def staff_member_params
    params.require(:staff_member).permit(:username, :email)
  end
end

app/controllers/admin/staff_members_controller.rb
class Admin::StaffMembersController < Admin::BaseController
  # GET /staff_members
  def index
    @staff_members = StaffMember.includes(:company).order(id: :desc)
  end

  # GET /staff_members/:id
  def show
    @staff_member = StaffMember.find(params[:id])
  end

  # GET /staff_members/:id/edit
  def edit
    @staff_member = StaffMember.find(params[:id])
    @company_collection = load_company_collection
  end

  # PATCH /staff_members/:id
  def update
    @staff_member = StaffMember.find(params[:id])
    if @staff_member.update(staff_member_params)
      redirect_to admin_staff_member_path(@staff_member), notice: t("updated")
    else
      @company_collection = load_company_collection
      render :edit
    end
  end

  # DELETE /staff_members/:id
  def destroy
    StaffMember.destroy(params[:id])
    redirect_to admin_staff_members_path, notice: t("deleted")
  end

  private

  def load_company_collection
    Company.all.map { |c| [c.name, c.id] }
  end

  def staff_member_params
    params.require(:staff_member).permit(:company_id, :username, :email)
  end
end

app/views/admin/staff_members/_form.html.erb
<% staff_member = local_assigns[:staff_member] %>
<% company_collection = local_assigns[:company_collection] %>

<%= form_with model: [:admin, staff_member], local: true do |f| %>
  <%= render "shared/model_errors", model: staff_member %>

  <div class="field">
    <%= f.label :company_id, class: "label" %>
    <div class="control">
      <div class="select">
        <%= f.select :company_id, company_collection %>
      </div>
    </div>
  </div>

  <div class="field">
    <%= f.label :username, class: "label" %>
    <%= f.text_field :username, class: "input" %>
  </div>

  <div class="field">
    <%= f.label :email, class: "label" %>
    <%= f.email_field :email, class: "input" %>
  </div>

  <div class="field">
    <div class="control">
      <%= f.submit nil, class: "button is-link" %>
    </div>
  </div>
<% end %>

app/views/admin/staff_members/edit.html.erb
<h1 class="title"><%= t ".title" %></h1>

<div class="content is-medium">
  <%= render "form", staff_member: @staff_member, company_collection: @company_collection %>
</div>

app/views/admin/staff_members/index.html.erb
<h1 class="title"><%= t ".title" %></h1>

<div class="content is-medium">
  <table class="table is-striped is-hoverable">
    <thead>
      <tr>
        <th><%= t "id" %></th>
        <th><%= t "activerecord.attributes.staff_member.company_id" %></th>
        <th><%= t "activerecord.attributes.staff_member.username" %></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @staff_members.each do |staff_member| %>
        <tr>
          <th><%= staff_member.id %></th>
          <td><%= link_to staff_member.company.name, admin_company_path(staff_member.company) %></td>
          <td><%= staff_member.username %></td>
          <td>
            <div class="columns">
            <div class="column">
            <%= link_to t("show"), admin_staff_member_path(staff_member), class: "button" %>
            </div>
            <div class="column">
            <%= link_to t("edit"), edit_admin_staff_member_path(staff_member), class: "button" %>
            </div>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/staff_members/show.html.erb
<div class="level">
  <div class="level-left">
    <h1 class="title">ID: <%= @staff_member.id %> - <%= @staff_member.username %></h1>
  </div>
  <div class="level-right">
    <div class="columns">
      <div class="column">
        <%= link_to t("edit"), edit_admin_staff_member_path(@staff_member), class: "button" %>
      </div>
      <div class="column">
        <%= link_to t("delete"), admin_staff_member_path(@staff_member), class: "button is-danger", method: :delete, data: { confirm: t("delete_confirm") } %>
      </div>
    </div>
  </div>
</div>

<div class="content is-small">
  <h3><%= t "activerecord.attributes.staff_member.company_id" %></h3>
  <p><%= link_to @staff_member.company.name, admin_company_path(@staff_member.company) %></p>

  <% %i(username email).each do |attribute| %>
    <h3><%= t "activerecord.attributes.staff_member.#{attribute}" %></h3>
    <p><%= @staff_member.public_send(attribute) %></p>
  <% end %>
</div>