config/routes.rb
Rails.application.routes.draw do
  # For common users
  scope module: "web" do
    constraints subdomain: "www" do
      root to: "home#index"

      get    "login",  to: "sessions#new",     as: :login
      delete "logout", to: "sessions#destroy", as: :logout

      get "confirmations", to: "confirmations#create", as: :confirmations

      # resources :bookings, only: %i(index edit update destroy)
      resources :sessions, only: %i(create)
      # resources :studios, only: %i(index show) do
      #   scope module: :studios do
      #     resources :bookings, only: %i(new create)
      #   end
      # end
      resources :users, only: %i(new create)

      resource :resend_confirmation_email, only: %i(new create)
      resource :setting, only: %i(edit update)
    end
  end

  # For studio staff
  scope module: "biz", as: :biz do
    constraints subdomain: "biz" do
      root to: "home#index"

      get    "login",  to: "sessions#new"
      delete "logout", to: "sessions#destroy"

      # resources :bookings, only: %i(index show)
      resources :sessions, only: %i(create)
      # resources :staff_members
      # resources :studios do
      #   scope module: :studios do
      #     resources :bookings
      #     resources :rooms
      #   end
      # end

      # resource :company, only: %i(show edit update)
      # resource :setting, only: %i(edit update)
    end
  end

  # For administrator
  scope module: "admin", as: :admin do
    constraints subdomain: "admin" do
      root to: "home#index"

      get    "login",  to: "sessions#new"
      delete "logout", to: "sessions#destroy"

      # resources :admin_users
      resources :companies do
        scope module: :companies do
          resources :staff_members, only: %i(new create)
        end
      end
      resources :sessions, only: %i(create)
      resources :staff_members, only: %i(index show edit update destroy)
    end
  end
end

app/views/layouts/web/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t "web.title" %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <%= link_to root_path, class: "navbar-item" do %>
          <p>Rails Playground</p>
        <% end %>

        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
          <%= link_to "#", class: "navbar-item" do %>
            Home
          <% end %>

          <%= link_to "#", class: "navbar-item" do %>
            Documentation
          <% end %>

          <div class="navbar-item has-dropdown is-hoverable">
            <%= link_to "#", class: "navbar-link" do %>
              More
            <% end %>

            <div class="navbar-dropdown">
              <%= link_to "#", class: "navbar-item" do %>
                About
              <% end %>
              <%= link_to "#", class: "navbar-item" do %>
                Jobs
              <% end %>
              <%= link_to "#", class: "navbar-item" do %>
                Contact
              <% end %>
              <hr class="navbar-divider">
              <%= link_to "#", class: "navbar-item" do %>
                Report an issue
              <% end %>
            </div>
          </div>
        </div>

        <div class="navbar-end">
          <div class="navbar-item">
            <div class="buttons">
              <% if current_user %>
                <%= link_to edit_setting_path, class: "button" do %>
                  Setting
                <% end %>
                <%= link_to logout_path, method: :delete, data: { confirm: t("logout_confirm") }, class: "button is-danger" do %>
                  Logout
                <% end %>
              <% else %>
                <%= link_to new_user_path, class: "button is-primary" do %>
                  <strong>Sign up</strong>
                <% end %>
                <%= link_to login_path, class: "button is-light" do %>
                  Log in
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </nav>
    <section class="section">
      <div class="container">
        <% flash.each do |name, msg| %>
          <div class="notification <%= name %>"><%= msg %></div>
        <% end %>

        <%= yield %>
      </div>
    </section>
  </body>
</html>